name:                reagan
version:             0.1.0.0
github:              "githubuser/reagan"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/reagan#readme>

dependencies:
- base >= 4.7 && < 5
- process
- temporary
- directory
- bytestring
- pcre-light
- pcre-heavy
- pipes
- safe
- time
- filepath
- strict
- deepseq
- transformers
- shelly
- megaparsec
- parser-combinators
- conduit
- resourcet
- streamly

library:
  source-dirs: src

executables:
  reagan-exe:
    main:                Main
    source-dirs:         app/reagan
    ghc-options:
    - -rtsopts
    - -O2
    dependencies:
    - reagan
  ub-query-exe:
    main:                Main
    source-dirs:         app/ub-query
    ghc-options:
    - -rtsopts
    - -O2
    dependencies:
    - reagan
  cv-query-exe:
    main:                Main
    source-dirs:         app/cv-query
    ghc-options:
    - -rtsopts
    - -O2
    dependencies:
    - reagan

tests:
  reagan-test:
    main:                Parser.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reagan
    - tasty
    - tasty-golden
    - Glob
